CREATE TYPE IF NOT EXISTS gender_enum AS ENUM ('MALE', 'FEMALE', 'RATHER_NOT_TO_SAY');
CREATE TYPE IF NOT EXISTS user_status AS ENUM ('ACTIVE', 'SUSPENDED', 'BANNED', 'DELETED');
CREATE TYPE IF NOT EXISTS post_category AS ENUM ('NORMAL', 'COMMENT', 'REPOST', 'QUOTE');
CREATE TYPE IF NOT EXISTS event_type AS ENUM ('VIEW_POST', 'LIKE_POST', 'DISLIKE_POST', 'CREATE_COMMENT', 'REPOST_POST', 'FOLLOW_USER', 'UNFOLLOW_USER', 'VIEW_PROFILE', 'CREATE_POST', 'REQUEST_FEED', 'LOGIN');
CREATE DOMAIN IF NOT EXISTS jsonb AS JSON;
