site_name: 🌳 Sarv (سرو)
site_url: https://ferigeek.github.io/sarv/
docs_dir: docs
site_dir: site
repo_url: https://github.com/ferigeek/sarv
repo_name: ferigeek/sarv

theme:
  name: material
  language: en
  features:
    - navigation.top
    - navigation.tracking
    - search.suggest
    - search.highlight
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: light green
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: light green
      accent: red
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  icon:
    repo: material/git

plugins:
  - search
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          name: English
          build: true
          default: true
          nav:
            - Home: index.md
            - Proposal: 1-Proposal.md
            - Requirements: 2-Requirements.md
            - Architecture: 3-Architecture.md
            - Database: 4-Database.md
        - locale: fa
          name: فارسی
          build: true
          default: false
          theme:
            direction: rtl
          nav:
            - خانه: index.md
            - پیشنهاده: 1-Proposal.md
            - نیازمندی‌ها: 2-Requirements.md
            - معماری: 3-Architecture.md
            - پایگاه داده: 4-Database.md


extra:
  alternate:
    - name: English
      link: /en/
      lang: en
    - name: فارسی
      link: /fa/
      lang: fa

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
